Repository nephio-project/nephio-example-packages, pull requests merged in 2023-05, with the labels that each got.

#5 Add example package showing direct use of PackageVariant
  free5gc-smf-org-example/Kptfile
  free5gc-smf-org-example/README.md
  free5gc-smf-org-example/package-context.yaml
  free5gc-smf-org-example/packagevariant.yaml
Labels: lgtm, approved

#7 Create initial version of UERANSIM kpt package - new repo
  ueransim/Kptfile
  ueransim/README.md
  ueransim/gnb/gnb-configmap.yaml
  ueransim/gnb/gnb-deployment.yaml
  ueransim/gnb/gnb-n2-nad.yaml
  ueransim/gnb/gnb-n3-nad.yaml
  ueransim/gnb/gnb-service.yaml
  ueransim/namespace.yaml
  ueransim/package-context.yaml
  ueransim/ue/ue-configmap.yaml
  ueransim/ue/ue-deployment.yaml
Labels: lgtm, approved, ok-to-test

#10 cluster-capi-kind package
  cluster-capi-kind/Kptfile
  cluster-capi-kind/README.md
  cluster-capi-kind/cluster.yaml
  cluster-capi-kind/cluster_class.yaml
  cluster-capi-kind/docker_cluster_template.yaml
  cluster-capi-kind/docker_machine_template_control_plane.yaml
  cluster-capi-kind/docker_machine_template_worker.yaml
  cluster-capi-kind/kubeadm_config_template.yaml
  cluster-capi-kind/kubeadm_controlplane_template.yaml
  cluster-capi-kind/package-context.yaml
Labels: lgtm, approved

#14 cert-manager package
  cert-manager/Kptfile
  cert-manager/README.md
  cert-manager/cert-manager.yaml
  cert-manager/package-context.yaml
Labels: lgtm, approved

#16 Cluster capi infrastructure docker package
  cluster-capi-infrastructure-docker/Kptfile
  cluster-capi-infrastructure-docker/README.md
  cluster-capi-infrastructure-docker/cluster-api-infrastructure-docker.yaml
  cluster-capi-infrastructure-docker/package-context.yaml
Labels: lgtm, approved

#8 Create packagevariantset.yaml example
  free5gc-smf-org-example/packagevariant.yaml
  free5gc-smf-org-example/packagevariantset.yaml
Labels: lgtm, approved

#13 gitea auto app.ini + admin user
  gitea/Kptfile
  gitea/README.md
  gitea/deployment-memcached.yaml
  gitea/namespace.yaml
  gitea/secret-gitea-init.yaml
  gitea/secret-gitea-inline-config.yaml
  gitea/secret-gitea.yaml
  gitea/service-gitea-http.yaml
  gitea/service-gitea-ssh.yaml
  gitea/service-http.yaml
  gitea/service-memcached.yaml
  gitea/service-postgresql-hl.yaml
  gitea/service-postgresql.yaml
  gitea/service-ssh.yaml
  gitea/statefulset-gitea.yaml
  gitea/statefulset-postgres.yaml
  gitea/statefulset.yaml
Labels: lgtm, approved

#17 Add package to deploy Nephio dev build of Porch
  porch-dev/0-packagerevs.yaml
  porch-dev/0-packagevariants.yaml
  porch-dev/0-packagevariantsets.yaml
  porch-dev/0-repositories.yaml
  porch-dev/1-namespace.yaml
  porch-dev/2-function-runner.yaml
  porch-dev/3-porch-server.yaml
  porch-dev/4-apiservice.yaml
  porch-dev/5-rbac.yaml
  porch-dev/6-rbac-bind.yaml
  porch-dev/7-auth-reader.yaml
  porch-dev/8-auth-delegator.yaml
  porch-dev/9-controllers.yaml
  porch-dev/9-porch-controller-clusterrole.yaml
  porch-dev/9-porch-controller-packagevariants-clusterrole.yaml
  porch-dev/9-porch-controller-packagevariants-clusterrolebinding.yaml
  porch-dev/9-porch-controller-packagevariantsets-clusterrole.yaml
  porch-dev/9-porch-controller-packagevariantsets-clusterrolebinding.yaml
  porch-dev/Kptfile
Labels: lgtm, approved

#20 resource backend
  resource-backend/Kptfile
  resource-backend/README.md
  resource-backend/app/Kptfile
  resource-backend/app/README.md
  resource-backend/app/controller/clusterrole-controller.yaml
  resource-backend/app/controller/clusterrolebinding-controller.yaml
  resource-backend/app/controller/deployment-controller.yaml
  resource-backend/app/controller/grpc/service-grpc.yaml
  resource-backend/app/controller/role-leader-election.yaml
  resource-backend/app/controller/rolebinding-leader-election.yaml
  resource-backend/app/controller/serviceaccount-controller.yaml
  resource-backend/crd/Kptfile
  resource-backend/crd/README.md
  resource-backend/crd/bases/ipam.alloc.nephio.org_ipallocations.yaml
  resource-backend/crd/bases/ipam.alloc.nephio.org_ipprefixes.yaml
  resource-backend/crd/bases/ipam.alloc.nephio.org_networkinstances.yaml
  resource-backend/crd/bases/vlan.alloc.nephio.org_vlanallocations.yaml
  resource-backend/crd/bases/vlan.alloc.nephio.org_vlandatabases.yaml
  resource-backend/crd/bases/vlan.alloc.nephio.org_vlans.yaml
  resource-backend/namespace.yaml
Labels: lgtm, approved

#27 Nephio controllers package
  nephio-controllers/Kptfile
  nephio-controllers/README.md
  nephio-controllers/app/Kptfile
  nephio-controllers/app/README.md
  nephio-controllers/app/controller/clusterrole-bootstrap.yaml
  nephio-controllers/app/controller/clusterrole-controller.yaml
  nephio-controllers/app/controller/clusterrole-repository.yaml
  nephio-controllers/app/controller/clusterrole-token.yaml
  nephio-controllers/app/controller/clusterrolebinding-bootstrap.yaml
  nephio-controllers/app/controller/clusterrolebinding-controller.yaml
  nephio-controllers/app/controller/clusterrolebinding-repository.yaml
  nephio-controllers/app/controller/clusterrolebinding-token.yaml
  nephio-controllers/app/controller/deployment-controller.yaml
  nephio-controllers/app/controller/role-leader-election.yaml
  nephio-controllers/app/controller/rolebinding-leader-election.yaml
  nephio-controllers/app/controller/serviceaccount-controller.yaml
  nephio-controllers/crd/Kptfile
  nephio-controllers/crd/README.md
  nephio-controllers/crd/bases/infra.nephio.org_repositories.yaml
  nephio-controllers/crd/bases/infra.nephio.org_tokens.yaml
  nephio-controllers/namespace.yaml
Labels: lgtm, approved

#25 rootsync package
  rootsync/Kptfile
  rootsync/README.md
  rootsync/package-context.yaml
  rootsync/rootsync.yaml
  rootsync/set-values.yaml
Labels: lgtm, approved

#23 configsync package
  configsync/Kptfile
  configsync/README.md
  configsync/config-management-operator.yaml
  configsync/configsync.yaml
  configsync/package-context.yaml
  configsync/rootsync-crd.yaml
Labels: lgtm, approved

#24 repository package
  repository/Kptfile
  repository/README.md
  repository/package-context.yaml
  repository/repo-gitea.yaml
  repository/repo-porch.yaml
  repository/set-values.yaml
  repository/token-configsync.yaml
  repository/token-porch.yaml
Labels: lgtm, approved

#26 cluster package
  nephio-workload-cluster/Kptfile
  nephio-workload-cluster/README.md
  nephio-workload-cluster/apply-replacements.yaml
  nephio-workload-cluster/package-context.yaml
  nephio-workload-cluster/pv-cluster.yaml
  nephio-workload-cluster/pv-configsync.yaml
  nephio-workload-cluster/pv-repo.yaml
  nephio-workload-cluster/pv-rootsync.yaml
Labels: lgtm, approved

#21 Add MetalLB package
  metallb/Kptfile
  metallb/README.md
  metallb/metallb-native.yaml
  metallb/package-context.yaml
Labels: lgtm, approved

#28 Fix repo package name
  nephio-workload-cluster/pv-repo.yaml
Labels: approved

#30 Use the package name as the default if clusterName is not set
  repository/set-values.yaml
  rootsync/set-values.yaml
Labels: lgtm, approved

#31 Stock repositories for out-of-the-box content
  nephio-stock-repos/Kptfile
  nephio-stock-repos/README.md
  nephio-stock-repos/package-context.yaml
  nephio-stock-repos/repo-free5gc-packages.yaml
  nephio-stock-repos/repo-nephio-example-packages.yaml
Labels: lgtm, approved

#36 enabled specializers
  nephio-controllers/app/controller/deployment-controller.yaml
Labels: lgtm, approved

#35 Set auto-approval for PV-generated packages
  nephio-workload-cluster/pv-cluster.yaml
  nephio-workload-cluster/pv-configsync.yaml
  nephio-workload-cluster/pv-repo.yaml
  nephio-workload-cluster/pv-rootsync.yaml
Labels: lgtm, approved

#32 Add metal LB config for sandbox environment
  metallb-sandbox-config/Kptfile
  metallb-sandbox-config/README.md
  metallb-sandbox-config/ipaddresspool.yaml
  metallb-sandbox-config/l2advertisement.yaml
  metallb-sandbox-config/package-context.yaml
Labels: lgtm, approved

#22 Add update packages script
  .gitignore
  cert-manager/cert-manager.yaml
  cluster-capi/cluster-api-bootstrap.yaml
  cluster-capi/cluster-api-control-plane.yaml
  cluster-capi/cluster-api-core.yaml
  update_packages.sh
Labels: lgtm, approved

#33 Use a static LB IP
  gitea/secret-gitea-inline-config.yaml
  gitea/service-gitea-ssh.yaml
  gitea/service-gitea.yaml
Labels: lgtm, approved

#38 Add role and binding for the approval controller
  nephio-controllers/app/controller/clusterrole-approval.yaml
  nephio-controllers/app/controller/clusterrolebinding-approval.yaml
Labels: lgtm, approved

#41 Fix kindnet approval annotation
  nephio-workload-cluster/pv-kindnet.yaml
Labels: approved
