Repository nephio-project/nephio-example-packages, pull requests merged in 2023-06, with the labels that each got.

#42 Eliminate the use of package context manipulation
  cluster-capi-kind/Kptfile
  cluster-capi-kind/apply-replacements.yaml
  cluster-capi-kind/set-values.yaml
  cluster-capi-kind/workload-cluster.yaml
  nephio-controllers/app/controller/clusterrole-approval.yaml
  nephio-controllers/crd/bases/infra.nephio.org_workloadclusters.yaml
  nephio-workload-cluster/apply-replacements.yaml
  nephio-workload-cluster/pv-cluster.yaml
  nephio-workload-cluster/pv-configsync.yaml
  nephio-workload-cluster/pv-kindnet.yaml
  nephio-workload-cluster/pv-repo.yaml
  nephio-workload-cluster/pv-rootsync.yaml
  nephio-workload-cluster/workload-cluster.yaml
  repository/set-values.yaml
  repository/workload-cluster.yaml
  rootsync/set-values.yaml
  rootsync/workload-cluster.yaml
Labels: lgtm, approved

#44 Add local-path-provisioner.
  local-path-provisioner/Kptfile
  local-path-provisioner/README.md
  local-path-provisioner/clusterrole.yaml
  local-path-provisioner/clusterrolebinding.yaml
  local-path-provisioner/configmap.yaml
  local-path-provisioner/deployment.yaml
  local-path-provisioner/namespace.yaml
  local-path-provisioner/serviceaccount.yaml
  local-path-provisioner/storageclass.yaml
Labels: lgtm, approved

#46 Use :latest images for Porch for now
  porch-dev/2-function-runner.yaml
  porch-dev/3-porch-server.yaml
  porch-dev/9-controllers.yaml
Labels: lgtm, approved

#45 Add local-path-provisioner pv into workload cluster.
  nephio-workload-cluster/pv-local-path-provisioner.yaml
Labels: lgtm, approved

#47 Reduce number of workers to 1
  cluster-capi-kind/cluster.yaml
Labels: lgtm, approved, ok-to-test

#48 resource backend with new apis
  resource-backend/app/controller/clusterrole-controller.yaml
  resource-backend/app/controller/deployment-controller.yaml
  resource-backend/crd/bases/inv.nephio.org_endpoints.yaml
  resource-backend/crd/bases/inv.nephio.org_links.yaml
  resource-backend/crd/bases/inv.nephio.org_nodes.yaml
  resource-backend/crd/bases/inv.nephio.org_targets.yaml
  resource-backend/crd/bases/ipam.resource.nephio.org_ipclaims.yaml
  resource-backend/crd/bases/ipam.resource.nephio.org_ipprefixes.yaml
  resource-backend/crd/bases/ipam.resource.nephio.org_networkinstances.yaml
  resource-backend/crd/bases/topo.nephio.org_rawtopologies.yaml
  resource-backend/crd/bases/vlan.resource.nephio.org_vlanclaims.yaml
  resource-backend/crd/bases/vlan.resource.nephio.org_vlanindices.yaml
  resource-backend/crd/bases/vlan.resource.nephio.org_vlans.yaml
Labels: lgtm, approved

#49 added vlanindex package
  nephio-workload-cluster/pv-vlanindex.yaml
  vlanindex/Kptfile
  vlanindex/README.md
  vlanindex/package-context.yaml
  vlanindex/set-values.yaml
  vlanindex/vlanindex.yaml
  vlanindex/workload-cluster.yaml
Labels: lgtm, approved

#50 network package
  network/Kptfile
  network/README.md
  network/package-context.yaml
  network/vpc-internal.yaml
  network/vpc-internet.yaml
  network/vpc-ran.yaml
Labels: lgtm, approved

#52 fixes for vlanindexes
  nephio-workload-cluster/pv-vlanindex.yaml
  vlanindex/vlanindex.yaml
Labels: lgtm, approved

#53 add parameters for specialization in nephio-workload-cluster
  nephio-workload-cluster/workload-cluster.yaml
Labels: lgtm, approved

#56 Switch to generic from separate ipam, vlan specializers
  nephio-controllers/app/controller/deployment-controller.yaml
Labels: lgtm, approved

#59 Nephio operator
  nephio-controllers/app/controller/clusterrole-network.yaml
  nephio-controllers/app/controller/clusterrole-porch.yaml
  nephio-controllers/app/controller/clusterrolebinding-network.yaml
  nephio-controllers/app/controller/clusterrolebinding-porch.yaml
  nephio-controllers/app/controller/deployment-controller.yaml
  nephio-controllers/app/controller/deployment-token-controller.yaml
Labels: lgtm, approved

#60 Add multus to workload clusters
  multus/Kptfile
  multus/README.md
  multus/multus-daemonset-thick.yml
  multus/package-context.yaml
  nephio-workload-cluster/pv-multus.yaml
Labels: approved

#63 split n2 n3
  network/vpc-ran.yaml
Labels: lgtm, approved

#62 network-config operator
  network-config/Kptfile
  network-config/README.md
  network-config/app/Kptfile
  network-config/app/README.md
  network-config/app/controller/clusterrole-controller.yaml
  network-config/app/controller/clusterrole-network.yaml
  network-config/app/controller/clusterrole-target.yaml
  network-config/app/controller/clusterrolebinding-controller.yaml
  network-config/app/controller/clusterrolebinding-network.yaml
  network-config/app/controller/clusterrolebinding-target.yaml
  network-config/app/controller/deployment-controller.yaml
  network-config/app/controller/role-leader-election.yaml
  network-config/app/controller/rolebinding-leader-election.yaml
  network-config/app/controller/serviceaccount-controller.yaml
  network-config/crd/Kptfile
  network-config/crd/README.md
  network-config/namespace.yaml
Labels: lgtm, approved

#65 updated image to nephio docker + init variables
  network-config/app/controller/deployment-controller.yaml
Labels: lgtm, approved

#66 specialization with ueransim
  ueransim/Kptfile
  ueransim/apply-replacements-namespace.yaml
  ueransim/apply-replacements-owner.yaml
  ueransim/gnb/gnb-configmap.yaml
  ueransim/gnb/gnb-deployment.yaml
  ueransim/gnb/gnb-n2-nad.yaml
  ueransim/gnb/gnb-n3-nad.yaml
  ueransim/gnb/service_gnb-service.yaml
  ueransim/interface-n2.yaml
  ueransim/interface-n3.yaml
  ueransim/ipclaim_amf-regional-n2-ipv4.yaml
  ueransim/namespace.yaml
  ueransim/network_vpc-internal.yaml
  ueransim/network_vpc-internet.yaml
  ueransim/network_vpc-ran.yaml
  ueransim/ue/ue-configmap.yaml
  ueransim/ue/ue-deployment.yaml
  ueransim/workload-cluster.yaml
Labels: lgtm, approved

#67 update service
  ueransim/gnb/service_gnb-service.yaml
Labels: lgtm, approved

#68 ueransim service
  ueransim/gnb/service_gnb-service.yaml
Labels: lgtm, approved

#69 Use v1.0.0 tag
  nephio-controllers/app/controller/deployment-controller.yaml
  nephio-controllers/app/controller/deployment-token-controller.yaml
  network-config/app/controller/deployment-controller.yaml
  porch-dev/2-function-runner.yaml
  porch-dev/3-porch-server.yaml
  porch-dev/9-controllers.yaml
  resource-backend/app/controller/deployment-controller.yaml
  ueransim/Kptfile
Labels: lgtm, approved
